opensafely-core/interactive-templates

smush.py
templates/v2/analysis/study_definition.py
templates/v2/analysis/study_definition_ethnicity.py
templates/v2/project.yaml.tmpl
tests/test_v2.py

- render time_* values from Louis fixes
- Move template file to be non-templated
- Render start/end dates into templates

Un-hardcode time_* and start/end dates

---

templates/v2/project.yaml.tmpl

The actions are potentially entirely unrelated to any previous actions.

Render the analysis id in the action names

---

templates/v2/project.yaml.tmpl

I think codelist 1's type is independent of codelist 2's type. If it isn't, then a comment explaining why would be helpful.

Fix codelist type

---

templates/v2/project.yaml.tmpl
tests/test_v2.py

This adds the title into the template. It's already stored within the Analysis object in Job Server, so it's already available to the template.

Pass in report title

---

templates/v2/analysis/populations.py

`age` is a categorical variable.  `age_years` is the variable we need

use age_years in population filters

---

templates/v2/analysis/render_report.py
templates/v2/project.yaml.tmpl

The path to the data was hardcoded to a dir that doesn't exist when run on real data

fix: use the request id to get the report data

---

interactive_templates/templates/v2/analysis/render_report.py
interactive_templates/templates/v2/project.yaml.tmpl
tests/test_v2.py

The job-server code will be switched back to this path when we update it
to this branch

Change the report output back to previous version

---

interactive_templates/schema/v2.py
interactive_templates/templates/v2/analysis/render_report.py
interactive_templates/templates/v2/analysis/report_template.html
interactive_templates/templates/v2/project.yaml.tmpl

- Use strict template rendering and fix it
- render images inline

inline images

---

interactive_templates/schema/v2.py
tests/test_v2.py

Companion changes to support opensafely-core/job-server#2850
Ref: opensafely-core/job-server#2845

Add purpose to v2.Analysis

---

interactive_templates/templates/v2/analysis/render_report.py
interactive_templates/templates/v2/analysis/report_template.html

This updates the report content:
* Reorganisaes the introduction (and renames this section)
* Adds in report limitations section
* Few other misc changes

update report content

---

DEVELOPERS.md
interactive_templates/schema/v2.py
interactive_templates/templates/v2/analysis/create_notebook.py
interactive_templates/templates/v2/analysis/render_report.py
interactive_templates/templates/v2/analysis/report_template.html
interactive_templates/templates/v2/project.yaml.tmpl
tests/test_render_cli.py

Ref: opensafely-core/job-server#2981

Remove report title

---

interactive_templates/templates/v2/analysis/event_counts.py
interactive_templates/templates/v2/analysis/report_template.html
interactive_templates/templates/v2/analysis/utilities.py

Practice-count-fix

---

interactive_templates/templates/v2/analysis/measures.py
interactive_templates/templates/v2/analysis/plot_measures.py
interactive_templates/templates/v2/analysis/render_report.py
interactive_templates/templates/v2/analysis/report_utils.py
interactive_templates/templates/v2/project.yaml.tmpl

This replaces the deciles chart reusable action with a scripted action. This allows us to apply custom formatting.
The formatting is consistent with the changes made to the other plots in #64.
Fixes #28

Deciles chart updates

---

interactive_templates/templates/v2/analysis/render_report.py
interactive_templates/templates/v2/analysis/report_template.html
interactive_templates/templates/v2/analysis/study_definition.py

The analysis code didn't completely handle the case where no demographics are selected. This updates the report template and report rendering script to handle this case.

Handle-no-demographics

---

interactive_templates/templates/v2/analysis/event_counts.py
interactive_templates/templates/v2/analysis/measures.py
interactive_templates/templates/v2/analysis/plot_measures.py
interactive_templates/templates/v2/analysis/render_report.py
interactive_templates/templates/v2/project.yaml.tmpl

Example of how a for loop in the template allows for action='append' arguments
Avoids needing to parse a comma separated string of breakdowns

Template breakdowns

---

interactive_templates/templates/v2/analysis/render_report.py
interactive_templates/templates/v2/analysis/report_template.html

And add classes so that we can easily style elements.

Update report template to use semantic HTML

---

interactive_templates/templates/v2/analysis/measures.py
interactive_templates/templates/v2/tests/test_measures.py

We refactored `measures.py` in https://github.com/opensafely-core/interactive-templates/pull/87. This PR extends the existing tests to cover the rest of the module

Test measures

---

interactive_templates/templates/v2/analysis/event_counts.py
interactive_templates/templates/v2/analysis/measures.py
interactive_templates/templates/v2/analysis/report_utils.py
interactive_templates/templates/v2/analysis/top_5.py
interactive_templates/templates/v2/project.yaml.tmpl

Fixes #104. The missing descriptions were due to long codes being truncated. Switching to feather fixes this.

Fix missing code descriptions

---

interactive_templates/schema/v2.py

This should help us catch errors when converting form values much
earlier.

Strictly validate schema field values

---

interactive_templates/schema/v2.py

Also, we don't currently use Analsysis.created_by or Analysis.repo, so
make those optional too

id needs to be optional

---

interactive_templates/templates/v2/analysis/render_report.py
interactive_templates/templates/v2/project.yaml.tmpl

This is more robust, and fixes a cli arg parsing bug in the
process.

Use config rather than cli arg for render action

---

interactive_templates/templates/v2/analysis/render_report.py
interactive_templates/templates/v2/analysis/report_template.html

Time value was being treated as a str but it's an int.
Fixes #156

fix type of time_value

---

interactive_templates/templates/v2/analysis/measures.py
interactive_templates/templates/v2/analysis/plot_measures.py
interactive_templates/templates/v2/analysis/render_report.py
interactive_templates/templates/v2/analysis/report_template.html
interactive_templates/templates/v2/project.yaml.tmpl
interactive_templates/templates/v2/tests/test_measures.py

Redacting plots

---

interactive_templates/templates/v2/analysis/measures.py
interactive_templates/templates/v2/analysis/plot_measures.py
interactive_templates/templates/v2/analysis/render_report.py
interactive_templates/templates/v2/analysis/top_5.py
interactive_templates/templates/v2/project.yaml.tmpl

Output checking measures

---

interactive_templates/templates/v2/analysis/report_template.html

show patients with events in report

---

interactive_templates/templates/v2/analysis/event_counts.py
interactive_templates/templates/v2/analysis/measures.py
interactive_templates/templates/v2/analysis/report_template.html
interactive_templates/templates/v2/analysis/top_5.py
interactive_templates/templates/v2/tests/test_event_counts.py
interactive_templates/templates/v2/tests/test_measures.py

add redaction info to report

---

justfile

Migrate to `docker compose` v2 command

---

DEVELOPERS.md

See #363.
This is not obvious to anyone not familiar with this repository.

Document the release process
