Dockerfile, justfile, pyproject.toml, templates/v2/analysis/measures.py, templates/v2/project.yaml.tmpl, templates/v2/tests/conftest.py, templates/v2/tests/test_measures.py
To fix the relative imports issue, we switch to running the script via
`python -m analysis.measures`. This allows us to use an absolute import
from within measures.py, which works both when run as an action, and
when importing for testing.
Also improved test-functional to work with running each templated
analysis in isolation. The previous sys.path munging had the potential
to break confusingly when we add a new templates analysis, so this is
much cleaner
=> Further tweaks running the tests in Docker

templates/v2/analysis/event_counts.py, templates/v2/analysis/render_report.py, templates/v2/analysis/report_template.html, templates/v2/project.yaml.tmpl
This addresses #35. This was simpler than expected because we were already producing the practice count, but it wasn't being used in the report.
The existing code is updated to round the practice count to the nearest 10, instead of nearest 100; we don't have to be as stringent for practice count as we are for patient population counts.
=> Practice count

templates/v2/analysis/top_5.py
The top 5 tables weren't showing the top 5. The tables [were sorted](https://github.com/opensafely-core/interactive-templates/blob/75a7bc31b99bd9b315b5f30c2148999b350ff604/templates/v2/analysis/top_5.py#L90), but  there was extra processing that reordered the tables before they were returned. This moves the sorting of the tables so it happens after all the other processing
=> Fix top 5 table

interactive_templates/render.py, interactive_templates/schema/v2.py
attrs doesn't validate inputs by default, so we add some validation of
the non-string types.
Also support csv lists for render cli args, so we can do `just render
demographics=age,sex`
=> fix: enforce typing in schema

interactive_templates/templates/v2/analysis/plot_measures.py, interactive_templates/templates/v2/analysis/report_utils.py
When we generate the underlying data for the reports, we redact low counts, replacing them with `[REDACTED]`. When redaction occurs, this changes the dtype of the column to plot to an object instead of a float. This results in the figure not rendering properly (see [the age band figure in this report](https://jobs.opensafely.org/datalab/opensafely-internal/opensafely-internal-interactive/releases/01GW265C3SHG1G2XS6JE6VF7MR/output/01GVZM1JMFYG87V8YQVR7AW8NX/report.html))
This adds in a change to ensure the column to be plotted is a float, so the figure renders properly.
It also refactors the function used to plot the figures to make them more legible.
=> Fix age bands

.github/workflows/create-job-server-pr.yml, DEVELOPERS.md
I temporarily enabled this to trigger on `pull_request` in order to test it. 
It successfully created a job-server PR that DTRT and passed tests: https://github.com/opensafely-core/job-server/pull/3024
I have not enabled automerge for now, so we can suck it an see for a bit.
=> Add workflow to create job-server PR on push to main

interactive_templates/schema/v2.py, interactive_templates/templates/v2/analysis/event_counts.py, interactive_templates/templates/v2/analysis/report_template.html, interactive_templates/templates/v2/analysis/report_utils.py, interactive_templates/templates/v2/analysis/study_definition.py, interactive_templates/templates/v2/project.yaml.tmpl, tests/test_v2.py
This adds a count of the number of events in the latest week to the report. This requires an additional action the pipeline to extract a single weekly cohort, which uses the same study definition as the monthly extracts but with different paramaterisation. It also required some changes to the date handling within the study definition - this isn't very nice because we're having to dynamically create string representation of dates that can be handled by cohort extractor. I'm not sure if there's a better way - this will only get more messy as we add support for forward lookup or want to update the comparison date for codelist 2 (to something other than the end date of the week/month).
Note: this requires one more value to be passed to the analysis code.  I've called it `weekly_start_date`, …
=> Events in latest week

interactive_templates/templates/v2/analysis/report_template.html, interactive_templates/templates/v2/tests/test_report_utils.py, tests/test_v2.py
https://github.com/opensafely-core/job-server/pull/3038 adds the option to specify 0 for `time_value`. We want to make sure this is handled correctly by the analysis code. This adds a test for `calculate_variable_windows_codelist_2` to check the study def specification is as we expect and then updates the functional tests to include a parameter set with `time_value=0` to check cohortextractor handles what we're passing it.
=> Handle "0 weeks before" correctly.

interactive_templates/templates/v2/analysis/report_template.html
- Make all links open in new tabs
- Improve formatting of lists turned in to comma separated text
- Add option for `data-format-number="true"` to allow JS styling of numbers
=> Formatting fixes for the report template

.gitignore, interactive_templates/render.py, interactive_templates/templates/v2/analysis/config.py, interactive_templates/templates/v2/analysis/study_definition.py, interactive_templates/templates/v2/analysis/study_definition_ethnicity.py, interactive_templates/templates/v2/project.yaml.tmpl, tests/test_render_cli.py
Serialising the config into cli args and parsing it was source of bugs.
Instead, we render the *validated* form input as json, and then load
that to access the data in the code.
Everything is validated and typed correctly, no more hand parsing
needed. And simplifies the project.yaml to be more readable.
We do re-use the study definition in the weekly action, so make those
still overloadable via cohortextractor parameters.
=> Render json config and use it instead of passing cli args

tests/test_v2.py
Previouisly, we only ran the study definitions, to avoid the long run
time for the full chain.
Buy render_report.py also uses time_ever, and had a bug we didn't catch
because of this.
This increases the tests run time by about 30s on my computer
=> Run all actions for time_ever functional tests

interactive_templates/templates/v2/analysis/event_counts.py, interactive_templates/templates/v2/analysis/plot_measures.py, interactive_templates/templates/v2/analysis/report_template.html, interactive_templates/templates/v2/analysis/report_utils.py
- Makes redacted event counts show as `[REDACTED]` instead of 0.
- Orders legend for the age plot, and shows the outer deciles in the deciles chart legend.
- Makes the rate denominator clear.
- Fixes figure styling
- Updates colour palette so lines are more distinguishable
- Makes x ticks less frequent
- Applies styling consistently to all charts.
In passing,  addresses #147. In seaborn, missing data is not extrapolated over when plotting a line chart.
=> Figure fixes

interactive_templates/templates/v2/analysis/event_counts.py, interactive_templates/templates/v2/tests/test_event_counts.py
Fixes #160 .
Whilst here, it also deals with the outstanding TODO for events counts. We had been calculating all summary counts using a subset of the data where only practices with events were included. As we're including the total population in the summary counts, this should include patients within "zero practices".
=> Fix practice count

.github/workflows/auto-merge-dependabot-prs.yml, MANIFEST.in, docs/adr/0000-record-architecture-decisions.md, docs/adr/0001-manually-approve-dependabot-changes.md
This workflow gives the impression that any Dependabot changes are auto-deployed, but that's not currently the case. Rather than fixing it, we've decided that we will manually approve all Dependabot PRs, which will then be deployed as soon as we merge them. The ADR has more information about the reasoning.
=> Remove Dependabot auto-merge function

.github/workflows/main.yml
See #363.
As things stand, GitHub Actions can clone the repository without all existing tags. If the `version` hasn't been updated, then this `tag-new-release` workflow job will always tag the commit being checked out with the tag in `version`. As this tag should already exist from a previous run of this workflow, the `git push --tags` step fails.
=> Fetch all commits when tagging new release

DEVELOPERS.md
Missed this previously, but just spotted that there is a workflow that triggers opening a job-server PR, when a new release is available.
=> Refer to automated job-server PR creation

interactive_templates/templates/v2/tests/test_measures.py
For the current state of the code, this change is not required. It will, however, save someone fixing this in future, when actually wanting to use a newer OpenSAFELY Python image.
However, the tests currently rely on a quirky behaviour of `.all()` in pandas that has been fixed.
In the version of pandas inside the `python:latest` image (v1.0.1), the behaviour is that `.all()` can return an `dtype=object` instead of a Boolean, and our tests as written pass.
In later versions of pandas, `.all()` returns a Boolean instead, and our tests fail.
We can rewrite the tests to work both prior to and post this pandas fix.
This was checked by running the tests with the `Dockerfile` as provided, and editing the `Dockerfile` to use the `v2` OpenSAFELY Python image.
See pandas-dev/pandas#12863.
=> Fix quirks in pandas test behaviour

interactive_templates/create.py, tests/test_create.py
Treating the URL (`repo`) as a string and checking if an allowed host is a substring of the URL is prone to errors. Instead, we parse the URL before performing a check on its host value.
Fixes #361
=> Handle arbitrary subdomain sequences correctly

requirements.dev.txt, requirements.prod.txt
Closes:
* https://github.com/opensafely-core/interactive-templates/security/dependabot/19
* https://github.com/opensafely-core/interactive-templates/security/dependabot/20
=> Bump certifi from 2024.6.2 to 2024.7.4

.github/workflows/create-job-server-pr.yml
job-server uses Python 3.12, so we need it here in this workflow, otherwise job-server's `just` recipe fails.
Thanks to @lucyb for realising what happened when we were chatting, saving me from investigating it.
=> Update Python to 3.12 for job-server PR workflow

.github/workflows/main.yml
`man bash` on `exit`:
> If n is omitted, the exit status is that of the last command executed.
If the `git tag` fails, then the exit status is then also an error code and GitHub Actions helpfully sends whoever triggered the workflow a notification.
=> Handle `git tag` failure more gracefully

.github/dependabot.yml
Because of the hybrid nature of this repo (Python 3.8/3.11), we're unable to keep updating Hypothesis. Given that OSI is "sunsetted", it seems reasonable to have Dependabot ignore it.
Fixes #423
=> Have Dependabot ignore Hypothesis
